export const url =  "https://jtlykjxgnadxtsgvwipj.supabase.co";
export const key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0bHlranhnbmFkeHRzZ3Z3aXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDU1ODM4MDUsImV4cCI6MjAyMTE1OTgwNX0.GavYajHKR8UYPlAyzL02VNpi5kY5qb0BTxTBqdZy2ps";
